// Generated by versions.py from versions.json. Do not edit.
window.DCLAB_VERSIONS = {
 "latest": "v3",
 "versions": [
  {
   "id": "v3",
   "name": "Clean",
   "date": "5 October 2026",
   "summary": "The product look: 10 screens, one job each, details behind tabs, plain words.",
   "pages": [
    "client.html",
    "data.html",
    "experiments.html",
    "governance.html",
    "graph.html",
    "home.html",
    "inbox.html",
    "index.html",
    "lab.html",
    "map.html",
    "models.html",
    "monitoring.html",
    "operator.html",
    "pipeline.html",
    "settings.html"
   ]
  },
  {
   "id": "v2",
   "name": "Detailed, tabbed",
   "date": "3 October 2026",
   "summary": "Every detail kept. 16 screens, larger type, dense cards split into section tabs, review notes on each page.",
   "pages": [
    "agents.html",
    "client.html",
    "data.html",
    "decisions.html",
    "experiments.html",
    "governance.html",
    "graph.html",
    "home.html",
    "improve.html",
    "inbox.html",
    "index.html",
    "lab.html",
    "map.html",
    "models.html",
    "monitoring.html",
    "operator.html",
    "pipeline.html",
    "settings.html"
   ]
  },
  {
   "id": "v1",
   "name": "Detailed",
   "date": "3 October 2026",
   "summary": "The first full walkthrough. 16 screens showing every field, id and review note.",
   "pages": [
    "agents.html",
    "client.html",
    "data.html",
    "decisions.html",
    "experiments.html",
    "governance.html",
    "graph.html",
    "home.html",
    "improve.html",
    "inbox.html",
    "index.html",
    "lab.html",
    "map.html",
    "models.html",
    "monitoring.html",
    "operator.html",
    "pipeline.html",
    "settings.html"
   ]
  }
 ]
};

(function () {
  var data = window.DCLAB_VERSIONS;
  var script = document.currentScript;
  var match = location.pathname.match(/\/(v\d+)\/([^\/]*)$/);
  var current = (match && match[1]) || (script && script.getAttribute('data-version'));
  var file = (match && match[2]) || 'index.html';
  var here = data.versions.filter(function (v) { return v.id === current; })[0];
  if (!here) return;

  var style = document.createElement('style');
  style.textContent =
    '.dcv{position:fixed;right:18px;bottom:18px;z-index:90;font:600 14px/1.3 -apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif}' +
    '.dcv-btn{font:inherit;display:inline-flex;align-items:center;gap:8px;padding:9px 14px;border-radius:999px;border:1px solid #CAD7D5;background:#fff;color:#15211E;cursor:pointer;box-shadow:0 6px 20px rgba(21,33,30,.12)}' +
    '.dcv-btn:hover,.dcv-btn:focus-visible{border-color:#1B88AE;outline:none}' +
    '.dcv-btn i{font-style:normal;color:#8B9A96}' +
    '.dcv-old .dcv-btn{background:#FBF1DD;border-color:#E3C98F}' +
    '.dcv-menu{position:absolute;right:0;bottom:calc(100% + 10px);width:min(340px,calc(100vw - 36px));background:#fff;border:1px solid #E3EAE9;border-radius:16px;padding:8px;box-shadow:0 20px 60px rgba(21,33,30,.2);display:grid;gap:2px}' +
    '.dcv-menu[hidden]{display:none}' +
    '.dcv-menu a{display:grid;gap:2px;padding:11px 12px;border-radius:10px;text-decoration:none;color:#15211E}' +
    '.dcv-menu a:hover,.dcv-menu a:focus-visible{background:#F4F8F8;outline:none}' +
    '.dcv-menu a[aria-current]{background:#EAF4EC}' +
    '.dcv-menu b{font-weight:650;display:flex;gap:8px;align-items:center}' +
    '.dcv-menu small{font-weight:400;font-size:13px;color:#586864;line-height:1.4}' +
    '.dcv-tag{font-size:12px;font-weight:650;color:#1F8A42;background:#E7F4EB;border-radius:999px;padding:1px 8px}' +
    '.dcv-all{border-top:1px solid #E3EAE9;margin-top:4px;border-radius:0 0 10px 10px!important;color:#1B88AE!important;font-weight:600}';
  document.head.appendChild(style);

  var box = document.createElement('div');
  box.className = 'dcv' + (current === data.latest ? '' : ' dcv-old');
  var number = current.replace('v', '');
  var items = data.versions.map(function (v) {
    var target = '../' + v.id + '/' + (v.pages.indexOf(file) > -1 ? file : 'index.html');
    return '<a href="' + target + '"' + (v.id === current ? ' aria-current="true"' : '') + '><b>Version ' + v.id.replace('v', '') + ' · ' + v.name +
      (v.id === data.latest ? ' <span class="dcv-tag">Latest</span>' : '') + '</b><small>' + v.date + ' · ' + v.summary + '</small></a>';
  }).join('');
  box.innerHTML = '<div class="dcv-menu" hidden>' + items + '<a class="dcv-all" href="../index.html">All versions</a></div>' +
    '<button class="dcv-btn" type="button" aria-haspopup="true" aria-expanded="false">Version ' + number + ' · ' + here.name +
    (current === data.latest ? '' : ' (older)') + ' <i aria-hidden="true">▴</i></button>';
  document.body.appendChild(box);

  var button = box.querySelector('.dcv-btn');
  var menu = box.querySelector('.dcv-menu');
  function toggle(open) { menu.hidden = !open; button.setAttribute('aria-expanded', open ? 'true' : 'false'); }
  button.addEventListener('click', function () { toggle(menu.hidden); });
  document.addEventListener('click', function (event) { if (!box.contains(event.target)) toggle(false); });
  document.addEventListener('keydown', function (event) { if (event.key === 'Escape') toggle(false); });
})();
