"""Transport-neutral DCLab client. Talks only to /v1 over HTTP."""

from dclab_client._http import DEFAULT_TIMEOUT_SECONDS, MAX_TIMEOUT_SECONDS
from dclab_client._version import USER_AGENT, __version__
from dclab_client.client import DCLabClient
from dclab_client.errors import (
    AuthenticationError,
    BadRequestError,
    ConflictError,
    DCLabAPIError,
    DCLabClientError,
    IdempotencyConflictError,
    NotFoundError,
    PermissionDeniedError,
    PreconditionFailedError,
    PreconditionRequiredError,
    RateLimitedError,
    ServerError,
    UnprocessableEntityError,
)
from dclab_client.types import (
    Artifact,
    Dataset,
    DecisionRecord,
    DecisionRecordPage,
    ErrorDetail,
    ErrorEnvelope,
    EventPage,
    ExecutionRequest,
    ExperimentCode,
    ModelBuild,
    ModelBuildEvent,
    NodeImpact,
    Principal,
    PrincipalWorkspace,
    Project,
    ProjectGraph,
    Visualization,
    Workspace,
)

__all__ = [
    "DEFAULT_TIMEOUT_SECONDS",
    "MAX_TIMEOUT_SECONDS",
    "USER_AGENT",
    "__version__",
    "Artifact",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "DCLabAPIError",
    "DCLabClient",
    "DCLabClientError",
    "Dataset",
    "DecisionRecord",
    "DecisionRecordPage",
    "ErrorDetail",
    "ErrorEnvelope",
    "EventPage",
    "ExecutionRequest",
    "ExperimentCode",
    "IdempotencyConflictError",
    "ModelBuild",
    "ModelBuildEvent",
    "NodeImpact",
    "NotFoundError",
    "PermissionDeniedError",
    "PreconditionFailedError",
    "PreconditionRequiredError",
    "Principal",
    "PrincipalWorkspace",
    "Project",
    "ProjectGraph",
    "RateLimitedError",
    "ServerError",
    "UnprocessableEntityError",
    "Visualization",
    "Workspace",
]
